categories:
    path: /categories
    controller: App\Controller\CategoriesController::index

category:
    path: /category/{id}
    controller: App\Controller\CategoriesController::category

reponse:
    path: /category/{id}/reponse
    controller: App\Controller\CategoriesController::category

home:
    path: /
    controller: App\Controller\CategoriesController::index

register:
    path: /register
    controller: App\Controller\RegisterController::index

login:
    path: /login
    controller: App\Controller\LoginController::index

register_done:
    path: /register
    controller: App\Controller\RegisterController::register
    methods: ['POST']

login_check:
    path: '/login_check'
    controller: 'App\Controller\LoginController::login'
    methods: ['POST']
